commonFileTypes = {
    "jpg": "Images",
    "jpeg": "Images",
    "png": "Images",
    "gif": "Images",
    "bmp": "Images",
    "ico": "Images",
    "svg": "Images",
    "webp": "Images",
    "tif": "Images",
    "tiff": "Images",
    "eps": "Images",
    "heic": "Images",
    "jfif": "Images", 
    "exe": "Executable Files",
    "msi": "Executable Files",
    "bat": "Executable Files",
    "cmd": "Executable Files",
    "ps1": "Executable Files",
    "vbs": "Executable Files",
    "msix": "Executable Files",
    "appinstaller": "Executable Files",
    "jar": "Executable Files",
    "dll": "Dynamic Link Library Files",
    "sys": "System Files",
    "ttf": "Fonts",
    "otf": "Fonts",
    "eot": "Fonts",
    "woff": "Fonts",
    "woff2": "Fonts",
    "zip": "Archives",
    "rar": "Archives",
    "7z": "Archives",
    "cab": "Archives",
    "gz": "Archives",
    "tar": "Archives",
    "zipx": "Archives",
    "pdf": "Documents",
    "doc": "Documents",
    "docx": "Documents",
    "txt": "Documents",
    "rtf": "Documents",
    "xls": "Documents",
    "xlsx": "Documents",
    "ppt": "Documents",
    "pptx": "Documents",
    "csv": "Documents",
    "pub": "Documents",
    "mp3": "Audio Files",
    "wav": "Audio Files",
    "ogg": "Audio Files",
    "flac": "Audio Files",
    "aac": "Audio Files",
    "mp4": "Video Files",
    "avi": "Video Files",
    "wmv": "Video Files",
    "mov": "Video Files",
    "webm": "Video Files",
    "mpg": "Video Files",
    "mpeg": "Video Files",
    "lnk": "Shortcut Files",
    "ini": "Configuration Files",
    "cfg": "Configuration Files",
    "log": "Log Files",
    "reg": "Registry Entries",
    "iso": "Disk Images",
    "img": "Disk Images",
    "vhd": "Virtual Hard Disk Files",
    "csv": "Data",
    "json": "Data",
    "xml": "Data",
    "html": "Web Files",
    "htm": "Web Files",
    "css": "Web Files",
    "js": "Web Files",
    "php": "Web Files",
    "asp": "Web Files",
    "py": "Scripts",
    "bat": "Scripts",
    "ps1": "Scripts",
    "sh": "Scripts",
    "c": "Scripts",
    "cpp": "Scripts",
    "sql": "Database Files",
    "db": "Database Files",
    "mdb": "Database Files",
    "accdb": "Database Files",
    "csv": "Spreadsheets",
    "xml": "Spreadsheets",
    "xlr": "Spreadsheets",
    "msg": "Emails",
    "eml": "Emails",
    "vcf": "Contacts",
    "ics": "Calendar",
    "bak": "Backup Files",
    "tmp": "Temporary Files",
    "ipynb": "Notebook Files", 
    "java": "Java Files",  
    "class": "Java Class Files",   
    "aex": "Adobe Files",
    "abr": "Adobe Files",
    "mogrt": "Adobe Files", 
    "psd": "Adobe Files",
    "ai": "Adobe Files",
    "prproj": "Adobe Files", 
    "aep": "Adobe Files",
    "fbx": "3D Files",
    "blend": "3D Files", 
    "obj": "3D Files",
    "amf": "3D Files",
    "iges": "3D Files", 
}
